# Generated by Django 4.0.1 on 2022-01-16 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='phone_numer',
            new_name='phone_number',
        ),
    ]
